name: Scan, Fix + Build Kakdela

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan-and-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps (if any)
        run: python -m pip install --upgrade pip

      - name: Run repository scanner
        run: |
          python3 .github/scripts/scan_repo.py --out report_dir
      - name: Upload scan report
        uses: actions/upload-artifact@v4
        with:
          name: repo-scan-report
          path: report_dir
          retention-days: 7

      - name: Run automatic fixer & setup (may modify files)
        run: |
          python3 .github/scripts/fix_and_setup.py

      - name: Show git status after fixes (for logs)
        run: |
          git --no-pager status --porcelain
          git --no-pager diff --name-only || true

      - name: Commit fixes (optional)
        if: steps['Run automatic fixer & setup'].conclusion == 'success'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "ci: automated fixes and setup by workflow"
            git push origin HEAD:main || true
          else
            echo "No changes to commit"
          fi

  build:
    needs: [scan-and-fix]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (fresh)
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Run Gradle build (uses gradle action to install Gradle)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kakdela-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: warn
          retention-days: 7
