name: scan_and_build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan_and_build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      ###########################################################
      # 1) Создание полноценного отчёта (БЕЗ ошибок)
      ###########################################################

      - name: Create scan report
        run: |
          echo "===== SCAN START =====" > scan_report.txt
          echo "" >> scan_report.txt
          echo "===== FILE TREE =====" >> scan_report.txt
          tree -a >> scan_report.txt

          echo "" >> scan_report.txt
          echo "===== FILE CONTENTS =====" >> scan_report.txt

          # перебор всех файлов, кроме больших бинарников
          find . -type f ! -name "*.apk" ! -path "./.git/*" | while read FILE; do
            echo "" >> scan_report.txt
            echo ">>> FILE: $FILE" >> scan_report.txt
            echo "----------------------------------------" >> scan_report.txt
            cat "$FILE" >> scan_report.txt 2>/dev/null || echo "[UNREADABLE]" >> scan_report.txt
          done

          echo "" >> scan_report.txt
          echo "===== SCAN END =====" >> scan_report.txt

      - name: Upload scan report
        uses: actions/upload-artifact@v4
        with:
          name: scan_report
          path: scan_report.txt

      ###########################################################
      # 2) Установка JDK
      ###########################################################

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      ###########################################################
      # 3) Исправление gradlew
      ###########################################################

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      ###########################################################
      # 4) Сборка APK
      ###########################################################

      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug --stacktrace

      ###########################################################
      # 5) Загрузка собранного APK
      ###########################################################

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kakdela-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
